version: '3.8'

services:

  backend:
    build: ./backend
    container_name: sentiment_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - TRANSFORMERS_CACHE=/app/cache

  ui:
    build: ./ui
    container_name: sentiment_ui
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app
    depends_on:
      - backend